---
- name: Sunuculari Temizle ve Docker-Portainer-NPM Kur
  hosts: all
  become: yes
  tasks:
    - name: 1. Cakisan Docker dosyalarini ve kilitleri sil
      shell: |
        rm -f /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock /etc/apt/sources.list.d/docker.list /etc/apt/keyrings/docker.gpg
        apt-get purge -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker.io docker-doc docker-compose podman-docker containerd runc
        apt-get update -y
      ignore_errors: yes

    - name: 2. Docker Deposu Hazirla
      shell: |
        apt-get install -y ca-certificates curl gnupg
        mkdir -m 0755 -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg --yes
        chmod a+r /etc/apt/keyrings/docker.gpg
        echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update -y

    - name: 3. Docker Paketlerini Yukle
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: 4. Portainer ve NPM Konteynerlerini Baslat
      shell: |
        docker volume create portainer_data || true
        docker rm -f portainer nginx-proxy-manager || true
        
        docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
        
        docker run -d --name nginx-proxy-manager --restart always -p 80:80 -p 81:81 -p 443:443 -v npm_data:/data -v npm_letsencrypt:/etc/letsencrypt jc21/nginx-proxy-manager:latest
