---
- name: "M-Cloud GPU Provisioning"
  hosts: all
  gather_facts: no

  tasks:
    # 1. ADIM: MODÜLÜ ZORLA KURDUR (Hata buradaydı, bu satır çözecek)
    - name: "Docker Koleksiyonunu Manuel Yukle"
      delegate_to: localhost
      ansible.builtin.command: ansible-galaxy collection install community.docker
      ignore_errors: yes

    # 2. ADIM: FULL VM PAKETİ
    - name: "FULL PAKET: Baslatiliyor"
      community.docker.docker_container:
        name: "mcloud_full_{{ 9999 | random }}"
        image: "dorowu/ubuntu-desktop-lxde-vnc"
        state: started
        published_ports:
          - "30500:80"
      when: user_choice == 'full_vm'

    # 3. ADIM: LIGHT PAKET
    - name: "LIGHT PAKET: Baslatiliyor"
      community.docker.docker_container:
        name: "mcloud_light_{{ 9999 | random }}"
        image: "ubuntu:latest"
        state: started
        command: sleep infinity
        published_ports:
          - "30501:22"
      when: user_choice == 'light_container'
